import {
  Injectable,
  CanActivate,
  ExecutionContext,
  ForbiddenException,
  Logger,
} from "@nestjs/common";
import { Reflector } from "@nestjs/core";

/**
 * Destructive actions that require explicit operator confirmation per D-30.
 *
 * These actions cannot be auto-executed by the agent — they require
 * a confirmation token validated server-side before execution.
 */
const DESTRUCTIVE_ACTION_PREFIXES = [
  "lockdown",
  "door_control",
  "control_door",
  "revoke_credential",
  "revoke_access",
];

const CONFIRMATION_HEADER = "x-confirmation-token";

/**
 * ActionConfirmationGuard enforces an explicit confirmation gate before
 * executing destructive agent actions (lockdown, door control, credential revoke).
 *
 * Per D-30: Destructive actions require operator confirmation.
 * The guard checks:
 * 1. Is the action destructive? (matched by name prefix)
 * 2. If destructive: is a confirmation token present in X-Confirmation-Token header?
 * 3. If no token: throw ForbiddenException requiring confirmation
 * 4. If token present: validate it (future: verify against Redis pending-action store)
 *
 * Follows RolesGuard structure: Reflector + CanActivate + ExecutionContext + ForbiddenException.
 */
@Injectable()
export class ActionConfirmationGuard implements CanActivate {
  private readonly logger = new Logger(ActionConfirmationGuard.name);

  constructor(private reflector: Reflector) {}

  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest();

    // Extract the action name from the request — could be in body.action,
    // body.toolName, or params.action
    const actionName: string | undefined =
      request.body?.action ??
      request.body?.toolName ??
      request.params?.action;

    if (!actionName) {
      // No action specified — not a destructive operation, allow
      return true;
    }

    // Check if this action is destructive
    const isDestructive = DESTRUCTIVE_ACTION_PREFIXES.some(
      (prefix) => actionName.toLowerCase().startsWith(prefix),
    );

    if (!isDestructive) {
      // Non-destructive action — allow
      return true;
    }

    // Destructive action — require confirmation token
    const confirmationToken =
      request.headers?.[CONFIRMATION_HEADER] ??
      request.body?.confirmationToken;

    if (!confirmationToken) {
      this.logger.warn(
        `Destructive action '${actionName}' blocked: no confirmation token from user ${request.user?.id ?? "unknown"}`,
      );
      throw new ForbiddenException(
        "Action nécessite une confirmation. Veuillez fournir un jeton de confirmation pour exécuter cette action destructive.",
      );
    }

    // TODO (future): Validate the confirmation token against a Redis-stored
    // pending action. For now, presence of a non-empty token in the header
    // is sufficient — the token is generated by the OrchestratorService
    // when the agent requests confirmation and verified via HMAC or UUID
    // comparison against the pending-action Redis store.
    if (typeof confirmationToken === "string" && confirmationToken.length > 0) {
      this.logger.log(
        `Destructive action '${actionName}' confirmed with token for user ${request.user?.id ?? "unknown"}`,
      );
      return true;
    }

    throw new ForbiddenException(
      "Jeton de confirmation invalide pour l'action destructive demandée.",
    );
  }
}
